### ISSUE TITLE
Did not kick VPN user

### ISSUE THREAD

**Issue by SpecialistNinja** [HiddenMotives/VPNGuard#11]
03.12 23:33:21 [Server] Server thread/INFO Player TestAccount has connected with the IP: 165.227.62.80
03.12 23:33:21 [Server] Server thread/INFO TestAccount joined the game.
03.12 23:33:22 [Server] Server thread/INFO TestAccount connected with a anonymizer
03.12 23:33:22 [Server] Server thread/INFO TestAccount Details -> ASN - DigitalOcean / Remaining API Requests: 56

**Comment by HiddenMotives** [comment]
You need to configure the plugin's command section, the default config.yml does nothing when a user with a VPN joins.

Configuring the plugin commands is super simple! Take a look at the config file: https://github.com/HiddenMotives/VPNGuard/blob/master/resources/config.yml it is pretty straight forward, the command section is a list of commands to run when a user joins with a VPN. %p represents the player name connecting and gets replaced automatically.

~~~~
command:
- kick %p You seem to be using a VPN or Proxy
~~~~
The above command to run would kick the player trying to connect with a VPN with the message "You seem to be using a VPN or Proxy". Or you could specify more than one command by adding another line like:
~~~~
command:
- kick %p You seem to be using a VPN or Proxy
- say %p is a naughty crafter.
~~~~
Which would both kick the player trying to connect to the server and broadcast "playerName is a naughty crafter"
