### ISSUE TITLE
correct configuration whitelist/blacklist country ip

### ISSUE THREAD

**Issue by teracube** [HiddenMotives/VPNGuard#12]
i need some information about whitelist/blacklist country ip

1 / is blacklist county ip works with VPN Basic key  (or Professionnal key needed)
https://vpnblocker.net/pricing

2/ what is the country list : iso2 or iso 3
http://kirste.userpage.fu-berlin.de/diverse/doc/ISO_3166.html

3/ what is the correct configuration ifi want to whitelist 4 country
is this config ok ?
in config.yml = country_mode: "whitelist"
in conntries.yml
FR
BE
US
CA

**Comment by HiddenMotives** [comment]
1. You need the Professional Key as it returns the country of the connecting IP

2. iso2 country code: https://github.com/HiddenMotives/VPNGuard/blob/master/src/basprohop/libraries/CommandFunctions.php#L205

3. You may use /vpnguard country add [iso2]

**Comment by teracube** [comment]
@HiddenMotives 
thanks
