### ISSUE TITLE
i can't use command vpnguard subnet {ban/unban} {ip/subnet block}

### ISSUE THREAD

**Issue by teracube** [HiddenMotives/VPNGuard#13]
is the synthax correct ?
when i type this command, console shows that is an incorrect command

vpnguard subnet ban 176.XXX.254.3

**Comment by HiddenMotives** [comment]
It would be /vpnguard subnet ban [ipv4 address/subnet]

Please see:
https://community.spiceworks.com/networking/articles/2495-what-is-cidr-notation
You may also use:
https://www.ipaddressguide.com/cidr

**Comment by teracube** [comment]
@HiddenMotives 
thanks : -)
