### ISSUE TITLE
VPNGuard crashing my server

### ISSUE THREAD

**Issue by NML32** [HiddenMotives/VPNGuard#3]
My PM hosting company VirtualGladiators just told me to stop using VPN Guard that it's crashing my server.
1. Don't use VPN Guard. It crashes your server. I've removed it:

Error: Call to a member function close() on null
File: /VPNGuard_v1.0.4.phar/src/basprohop/libraries/Async
Line: 53
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN
æ­¤æ¬¡åºéç±æä»¶å¼èµ·
BAD PLUGIN : VPNGuard v1.0.4

Please fix this so I can start using it again.

**Comment by HiddenMotives** [comment]
Hi, I see your using an outdated version, try with the newer one https://github.com/HiddenMotives/VPNGuard/tree/master/releases also what server software are you using? And verify if your host allows connection to tools.xioax.com

**Comment by NML32** [comment]
Thanks, I'll give that a try.

**Comment by NML32** [comment]
Still getting crashes on my Virtual Gladiators server.
Genisys Crash Dump Wed Jun 15 20:25:55 MDT 2016

Error: Call to a member function close() on null
File: /VPNGuard-1.0.5.phar/src/basprohop/libraries/Async
Line: 53
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

---

VG sent me this message when I opened a ticket with them for a unrelated issue.
 Don't use VPN Guard. It crashes your server. I've removed it:

VPNGuard is kind of a pain. If you don't buy their subscription, the server will either not start up or crash because of the limitations they have programmed into the plugin. With SimpleAuth or similar program, there should be no need for VPNGuard. We have hundreds of people running Pocketmine servers and very few use VPNGuard.

**Comment by HiddenMotives** [comment]
Hi, I would like to point out couple things, this particular version of VPNGuard has been developed for PocketMine and was not specifically created for it's forks. 

Secondly, although your specific error is an easy fix (i will push an update out to address the null pointer issue), it seems that your host is disallowing connections to the API server, or that your host's IP address has been previously blacklisted https://github.com/HiddenMotives/VPNGuard/blob/master/src/basprohop/libraries/Async.php#L51 there is definitely connection error from your VG server to the API server.

And finally to address your hosts response, you can't have client sided limitations, as they can be removed. Which I assume they are referring to https://github.com/HiddenMotives/VPNGuard/blob/master/src/basprohop/libraries/Async.php#L112 there is no hard coded limitation programmed into the plugin (if there was it could be removed), so I don't really know what they are talking about

**Comment by NML32** [comment]
Thanks

**Comment by NML32** [comment]
Just wondering when you will push out the update you mentioned above.

Thanks

**Comment by HiddenMotives** [comment]
I would Ideally like to bundle the update with couple of the other changes im working on, so it could take a couple

**Comment by NML32** [comment]
Sounds good thanks

**Comment by NML32** [comment]
Just curious when you will be releasing an update?

**Comment by HiddenMotives** [comment]
I know its been awhile but the release date is still unknown, just stay tuned

**Comment by NML32** [comment]
Is there going to be an update to VPNGuard to take advantage of XIOAX's new Professional tier?  
Maybe support for IP Geo Location with the ability to filter countries?

**Comment by HiddenMotives** [comment]
Of course country or city whitelist / blacklist  . Ability to lookup IP address or Player in-game etc.  It just been very difficult working on Pocketmine / PMMP plugins as the software is really buggy, constantly outdated and community is dying.

**Comment by NML32** [comment]
Great, I'm looking forward to the updates.
