### ISSUE TITLE
Is the plugin working ? (Block VPN ?)

### ISSUE THREAD

**Issue by MisteFr** [HiddenMotives/VPNGuard#4]

**Comment by MisteFr** [comment]
Working ! But the system of command when the ip is anonymous doesn't work where can i replace that by $player->close() in the code ?

**Comment by HiddenMotives** [comment]
Make sure you use the proper format when setting commands in the config.yml

~~~~
command:
- kick %p You seem to be using a VPN or Proxy
~~~~

And yes you may replace the foreach loop https://github.com/HiddenMotives/VPNGuard/blob/master/src/basprohop/libraries/Async.php#L75 with $player->close() if you really wish to do so.

**Comment by MisteFr** [comment]
Working thanks 👍
