### ISSUE TITLE
Getting error: Invalid API Key

### ISSUE THREAD

**Issue by NML32** [HiddenMotives/VPNGuard#6]
I getting an error with VPNGuard v1.0.6. My API key is linked to the Basic subscription.  Is the Basic plan no longer supported?

[20:18:34] [Server thread/WARNING]: API Server Returned Error Message: Invalid API Key when NML connected
[20:18:34] [Server thread/CRITICAL]: Shutting down server to prevent blacklisting on API Database

**Comment by HiddenMotives** [comment]
Hi, that's not possible, I did not make any such change. You need to contact the API provider and see if your account is still in good standing. Please update me so I can close this issue.

**Comment by NML32** [comment]
I've sent two emails but no response.
My other servers that are still running the older version Alpha6 are not getting that message.  
It could be a billing issue since I got an overdue payment message but I sent an email with my PP payment receipt. I'll continue to wait for a reply.

**Comment by HiddenMotives** [comment]
I suspect your other servers are not receiving this same error is because they are reading from the cache file. Anyways do update me when you get a response.

**Comment by NML32** [comment]
You are correct the issue was on the API provider's side. They have corrected the issue, sorry for the false alarm and thank you for your help.
