### ISSUE TITLE
what is the correct configuration

### ISSUE THREAD

**Issue by teracube** [HiddenMotives/VPNGuard#7]
Hi, 
What is the right configuration config.yml ?

1 or 2 or 3
thanks
sorry for my bad english

1)
You can purchase a key from: http://xioax.com/host-blocker/
api-key: "xxxapikeyxxx"

2)
You can purchase a key from: http://xioax.com/host-blocker/
api-key: xxxapikeyxxx

3)
You can purchase a key from: http://xioax.com/host-blocker/
api-key:xxxapikeyxxx

**Comment by HiddenMotives** [comment]
The first one
